# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g2G1CaZS517V-2_Y3ouFyN4dks8TPZlU
"""

def plot_upset(data = None):
  """
  plot an upset plot for missing data
  take an input a dataframe
  Example usage:
  import pandas as pd
  df = pd.read_csv("https://raw.githubusercontent.com/SalvatoreRa/tutorial/main/datasets/titanic.csv")
  plot_upset(data = df)
  """
  try:
    import upsetplot
  except ModuleNotFoundError:
    print("install upsetplot: !pip install upsetplot")
    pass
  import pandas as pd
  from upsetplot import plot, from_contents, from_indicators
  na_list = data.columns[data.isna().any()].tolist()
  data = data[data.columns.intersection(na_list)]
  data = data.mask(data.isnull()== True, True)
  data =data.mask(data != True, False)
  data =data.astype('bool')
  UpSet(from_indicators(data.columns.to_list(),data=data)).plot()